export const localKey = {
  BOARD_SELECTED_KEY: "BOARD_SELECTED_KEY",
  SELECTED_ITEM_ID_KEY: "SELECTED_ITEM_ID_KEY",

  BREAK_DURATION_KEY: "BREAK_DURATION_KEY",
  TARGET_MINUTES_KEY: "TARGET_MINUTES_KEY",
  AUTO_STOP_ENABLED: "AUTO_STOP_ENABLED",
} as const;
