export const localKey = {
  ACCESSIBILITY_PERMISSION: "ACCESSIBILITY_PERMISSION",
  BOARD_STORAGE_KEY: "BOARD_STORAGE_KEY",
  SCREEN_RECORDING_PERMISSION: "SCREEN_RECORDING_PERMISSION",
  IS_TRACKING: "IS_TRACKING",
  ACTIVITY_WINDOW: "ACTIVITY_WINDOW",
  IS_FOCUS_MODE: "IS_FOCUS_MODE",
};
