export const localKey = {
  BOARD_SELECTED_KEY: "BOARD_SELECTED_KEY",
  SELECTED_ITEM_ID_KEY: "SELECTED_ITEM_ID_KEY",

  BREAK_DURATION_KEY: "BREAK_DURATION_KEY",
  TARGET_MINUTES_KEY: "TARGET_MINUTES_KEY",
  AUTO_STOP_ENABLED: "AUTO_STOP_ENABLED",
  IS_UNLIMITED_FOCUS: "IS_UNLIMITED_FOCUS",
  IS_UNLIMITED_BREAK: "IS_UNLIMITED_BREAK",
  PLAY_START_SOUND: "PLAY_START_SOUND",
  PLAY_INTERVAL_SOUND: "PLAY_INTERVAL_SOUND",
  PLAY_COMPLETION_SOUND: "PLAY_COMPLETION_SOUND",
  PLAY_BREAK_START_SOUND: "PLAY_BREAK_START_SOUND",
  PLAY_BREAK_COMPLETION_SOUND: "PLAY_BREAK_COMPLETION_SOUND",
} as const;
