import { app, BrowserWindow, Tray, Menu, nativeImage, Notification } from "electron";
import registerListeners from "./helpers/ipc/listeners-register";
import * as path from "path";
import { ActivityRecord } from "./types/activity";

// "electron-squirrel-startup" seems broken when packaging with vite
//import started from "electron-squirrel-startup";

const inDevelopment: boolean = process.env.NODE_ENV === "development";

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let isQuiting: boolean = false;

async function createTray() {
  console.log("Main: Creating tray");
  // Request notification permission on macOS
  if (process.platform === "darwin") {
    await app.whenReady();
    if (!Notification.isSupported()) {
      console.log("Notifications not supported");
    }
  }

  const icon = nativeImage
    .createFromPath(path.join(__dirname, "../resources/icon.png"))
    .resize({ width: 18, height: 18 }); // Slightly larger for macOS

  // Set as template image for better dark/light mode support
  icon.setTemplateImage(true);

  tray = new Tray(icon);

  console.log("Main: Tray created");

  // Make sure tray icon is visible on Retina displays
  if (process.platform === "darwin") {
    tray.setPressedImage(icon);
  }

  const contextMenu = Menu.buildFromTemplate([
    {
      label: "Show",
      click: () => {
        if (mainWindow) {
          mainWindow.show();
          mainWindow.focus();
        }
      },
    },
    {
      label: "Quit",
      click: () => {
        app.quit();
      },
    },
  ]);

  tray.setContextMenu(contextMenu);
  tray.setToolTip("iTracksy");

  tray.setTitle("iTracksy");

  tray.on("click", () => {
    if (!mainWindow) {
      createWindow();
    } else {
      mainWindow.show();
      mainWindow.focus();
    }
  });
}

function createWindow(): void {
  const preload = path.join(__dirname, "preload.js");
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      devTools: true,
      contextIsolation: true,
      nodeIntegration: true,
      nodeIntegrationInSubFrames: false,
      preload: preload,
    },
    titleBarStyle: "hidden",
  });

  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  registerListeners(mainWindow, tray);
  console.log("Main: Registering listeners with tray", tray ? "defined" : "undefined");

  mainWindow.on("close", (event) => {
    if (!isQuiting) {
      event.preventDefault();
      mainWindow?.hide();
    }
  });
}

// Initialize app when ready
app.whenReady().then(async () => {
  await createTray();
  createWindow();
});

// Handle app quit
app.on("before-quit", () => {
  isQuiting = true;
});

//osX only
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  } else if (mainWindow) {
    mainWindow.show();
    mainWindow.focus();
  }
});
//osX only ends
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
  startTracking: (params: {
    accessibilityPermission: boolean;
    screenRecordingPermission: boolean;
    blockedDomains: string[];
    blockedApps: string[];
    isFocusMode: boolean;
  }) => Promise<void>;
  clearActivities: () => Promise<void>;
  getActivities: () => Promise<ActivityRecord[]>;
  updateTrayTitle: (title: string) => Promise<void>;
}

declare global {
  interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
  }
}

export {};
