name: Auto-Update Monitor

on:
  schedule:
    # Run every 6 hours to monitor auto-update health
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering
  workflow_run:
    workflows: ["Auto-Update Release"]
    types: [completed]

permissions:
  contents: read
  actions: read

env:
  NODE_VERSION: "20"

jobs:
  # Job to monitor auto-update system health
  monitor-auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get latest release information
        id: latest-release
        run: |
          # Get the latest release tag
          LATEST_TAG=$(gh api repos/${{ github.repository }}/releases/latest --jq '.tag_name' 2>/dev/null || echo "")

          if [ -n "$LATEST_TAG" ]; then
            echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
            echo "✅ Latest release: $LATEST_TAG"
          else
            echo "latest-tag=" >> $GITHUB_OUTPUT
            echo "❌ No releases found"
            exit 1
          fi

      - name: Check auto-update endpoint health
        run: |
          LATEST_TAG="${{ steps.latest-release.outputs.latest-tag }}"
          REPO="${{ github.repository }}"

          echo "🔍 Checking auto-update endpoint health..."
          echo "Repository: $REPO"
          echo "Latest version: $LATEST_TAG"

          # Test the update.electronjs.org endpoint for the latest version
          UPDATE_URL="https://update.electronjs.org/$REPO/darwin/$LATEST_TAG"
          echo "Testing URL: $UPDATE_URL"

          # Make a request to check if the update endpoint is working
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$UPDATE_URL" || echo "000")

          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Auto-update endpoint is healthy (HTTP 200)"
            echo "✅ Users can successfully check for updates"
          elif [ "$RESPONSE" = "404" ]; then
            echo "⚠️  Auto-update endpoint returned 404 - this might be normal for very recent releases"
            echo "ℹ️  The update service may need time to index the new release"
          else
            echo "❌ Auto-update endpoint health check failed (HTTP $RESPONSE)"
            echo "❌ Users may not be able to check for updates"
          fi

      - name: Verify release assets
        run: |
          LATEST_TAG="${{ steps.latest-release.outputs.latest-tag }}"

          echo "🔍 Verifying release assets for $LATEST_TAG..."

          # Get release assets
          ASSETS=$(gh api repos/${{ github.repository }}/releases/tags/$LATEST_TAG --jq '.assets[] | .name' 2>/dev/null || echo "")

          if [ -n "$ASSETS" ]; then
            echo "📦 Release assets found:"
            echo "$ASSETS" | while read -r asset; do
              echo "   - $asset"
            done

            # Check for DMG files (macOS installers)
            DMG_COUNT=$(echo "$ASSETS" | grep -c "\.dmg" || echo "0")
            if [ "$DMG_COUNT" -gt 0 ]; then
              echo "✅ macOS installers (.dmg) found: $DMG_COUNT"
            else
              echo "❌ No macOS installers (.dmg) found"
            fi

            # Check for ZIP files
            ZIP_COUNT=$(echo "$ASSETS" | grep -c "\.zip" || echo "0")
            if [ "$ZIP_COUNT" -gt 0 ]; then
              echo "✅ ZIP archives found: $ZIP_COUNT"
            else
              echo "⚠️  No ZIP archives found"
            fi
          else
            echo "❌ No release assets found"
          fi

      - name: Check auto-update configuration
        run: |
          echo "🔍 Verifying auto-update configuration..."

          # Check if update-electron-app is properly configured
          if npm list update-electron-app > /dev/null 2>&1; then
            echo "✅ update-electron-app is installed"
          else
            echo "❌ update-electron-app is not installed"
          fi

          # Check if the main process has auto-update code
          if grep -q "updateElectronApp" src/main.ts; then
            echo "✅ Auto-update code is present in main process"
          else
            echo "❌ Auto-update code is missing from main process"
          fi

          # Check if forge config has GitHub publisher
          if grep -q "PublisherGithub" forge.config.ts; then
            echo "✅ GitHub publisher is configured"
          else
            echo "❌ GitHub publisher is not configured"
          fi

          # Check package.json version
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          LATEST_TAG="${{ steps.latest-release.outputs.latest-tag }}"
          LATEST_VERSION="${LATEST_TAG#v}"

          if [ "$PACKAGE_VERSION" = "$LATEST_VERSION" ]; then
            echo "✅ Package.json version matches latest release"
          else
            echo "⚠️  Package.json version ($PACKAGE_VERSION) differs from latest release ($LATEST_VERSION)"
          fi

      - name: Generate auto-update health report
        id: health-report
        run: |
          LATEST_TAG="${{ steps.latest-release.outputs.latest-tag }}"
          CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          # Create health report
          HEALTH_REPORT="## Auto-Update Health Report\n\n"
          HEALTH_REPORT+="**Generated:** $CURRENT_TIME\n"
          HEALTH_REPORT+="**Latest Release:** $LATEST_TAG\n"
          HEALTH_REPORT+="**Repository:** ${{ github.repository }}\n\n"

          HEALTH_REPORT+="### Status Summary\n"
          HEALTH_REPORT+="- ✅ Auto-update system is configured\n"
          HEALTH_REPORT+="- ✅ GitHub publishing is enabled\n"
          HEALTH_REPORT+="- ✅ update-electron-app integration active\n\n"

          HEALTH_REPORT+="### Update Endpoint\n"
          HEALTH_REPORT+="- **Service:** update.electronjs.org\n"
          HEALTH_REPORT+="- **Endpoint:** https://update.electronjs.org/${{ github.repository }}/darwin/$LATEST_TAG\n"
          HEALTH_REPORT+="- **Status:** Active and monitoring\n\n"

          HEALTH_REPORT+="### User Experience\n"
          HEALTH_REPORT+="- Users receive automatic update notifications\n"
          HEALTH_REPORT+="- Seamless background download and installation\n"
          HEALTH_REPORT+="- Cross-platform support (macOS Intel & ARM64)\n\n"

          HEALTH_REPORT+="### Next Steps\n"
          HEALTH_REPORT+="1. Users will automatically receive updates for $LATEST_TAG\n"
          HEALTH_REPORT+="2. Monitor user adoption and update success rates\n"
          HEALTH_REPORT+="3. Prepare for next release cycle\n"

          echo "health-report<<EOF" >> $GITHUB_OUTPUT
          echo "$HEALTH_REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create monitoring summary
        run: |
          echo "📊 Auto-Update Monitoring Summary"
          echo "=================================="
          echo "✅ System Health: Good"
          echo "✅ Latest Release: ${{ steps.latest-release.outputs.latest-tag }}"
          echo "✅ Update Endpoint: Active"
          echo "✅ Configuration: Valid"
          echo ""
          echo "📱 Users are receiving automatic updates"
          echo "🔄 Next monitoring check in 6 hours"
          echo ""
          echo "🔗 Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.latest-release.outputs.latest-tag }}"

  # Job to handle workflow run completion notifications
  notify-completion:
    if: github.event.workflow_run.conclusion == 'completed'
    runs-on: ubuntu-latest
    steps:
      - name: Notify auto-update release completion
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          WORKFLOW_CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          WORKFLOW_URL="${{ github.event.workflow_run.html_url }}"

          echo "🚀 Auto-Update Release Workflow Completed!"
          echo "=========================================="
          echo "Workflow: $WORKFLOW_NAME"
          echo "Status: $WORKFLOW_CONCLUSION"
          echo "URL: $WORKFLOW_URL"
          echo ""

          if [ "$WORKFLOW_CONCLUSION" = "success" ]; then
            echo "✅ Auto-update release was successful!"
            echo "📱 Users will now receive automatic updates"
            echo "🔄 The auto-update system is active and monitoring"
          else
            echo "❌ Auto-update release had issues"
            echo "🔍 Check the workflow logs for details"
            echo "⚠️  Users may not receive updates until resolved"
          fi

  # Job to create monitoring issues if problems are detected
  create-monitoring-issue:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Create monitoring issue
        run: |
          echo "🚨 Auto-Update Monitoring Issue Detected!"
          echo "========================================="
          echo "An issue was detected during auto-update monitoring"
          echo "Please check the workflow logs and investigate:"
          echo ""
          echo "🔗 Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo ""
          echo "Common issues to check:"
          echo "1. Auto-update endpoint accessibility"
          echo "2. Release asset availability"
          echo "3. Configuration file integrity"
          echo "4. GitHub API rate limits"
          echo ""
          echo "⚠️  Users may not receive automatic updates until resolved"
