name: Release Windows

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

permissions:
  contents: write
  packages: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create data directories
        shell: bash
        run: |
          mkdir -p data
          mkdir -p out/make/data
          mkdir -p release/data
          mkdir -p dist/data

      - name: Build Windows executable (unsigned)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_AXIOM_TOKEN: ${{ secrets.VITE_AXIOM_TOKEN }}
          VITE_AXIOM_ORG_ID: ${{ secrets.VITE_AXIOM_ORG_ID }}
          VITE_AXIOM_DATASET: ${{ secrets.VITE_AXIOM_DATASET }}
          VITE_PUBLIC_POSTHOG_KEY: ${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}
          VITE_PUBLIC_POSTHOG_HOST: ${{ secrets.VITE_PUBLIC_POSTHOG_HOST }}
        run: |
          npm run make
          Write-Host "✅ Windows executable built successfully (unsigned)"
          Write-Host "⚠️  Note: This executable is unsigned and may trigger security warnings"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
